version: "3.8"

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/src/app # Monta el directorio actual
      - /usr/src/app/node_modules # Evita sobrescribir node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
